version: '3.6'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'git.exxo.top'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.exxo.top'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['custom_gitlab_server_config'] = 'if ($http_host != "git.exxo.top") { return 301 https://git.exxo.top$request_uri; }'
        # Add any other GitLab configurations here
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    tmpfs:
      - /var/opt/gitlab/gitlab-rails/tmp
    networks:
      gitlab_net:
        ipv4_address: 10.255.255.20 # <--- Using IP in the 10.255.255.x range

networks:
  gitlab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.255.255.0/24
