version: '3.6'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'git.exxo.top'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.exxo.top'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    tmpfs:
      - /var/opt/gitlab/gitlab-rails/tmp
    networks:
      gitlab_net:
        ipv4_address: 10.255.255.20 # <--- Using IP in the 10.255.255.x range
  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    restart: always
    depends_on:
      - gitlab
    volumes:
      - './runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - CI_SERVER_URL=https://git.exxo.top
    networks:
      gitlab_net:
        ipv4_address: 10.255.255.21

networks:
  gitlab_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.255.255.0/24
